miatoll: dolby: Address avc denial error
2025-03-26 14:46:36.669  2717-2872  ServiceManager          com.dolby.daxservice                 E  error in isDeclared
                                                                                                    java.lang.SecurityException: SELinux denied for service.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3261)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3245)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3228)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3170)
                                                                                                    	at android.os.IServiceManager.isDeclared(IServiceManager.java:606)
                                                                                                    	at android.os.ServiceManagerProxy.isDeclared(ServiceManagerNative.java:96)
                                                                                                    	at android.os.ServiceManager.isDeclared(ServiceManager.java:297)
                                                                                                    	at android.os.ServiceManager.waitForDeclaredService(ServiceManager.java:353)
                                                                                                    	at com.dolby.daxservice.hal.DmsHalAidl.connectService(DmsHalAidl.java:44)
                                                                                                    	at com.dolby.daxservice.hal.DmsHal.connectService(DmsHal.java:20)
                                                                                                    	at com.dolby.daxservice.DaxService.initDolbyHalClient(DaxService.java:463)
                                                                                                    	at com.dolby.daxservice.DaxService.-322Nest(DaxService.java:0)
                                                                                                    	at com.dolby.daxservice.DaxService.handleMessage(DaxService.java:270)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
2025-03-26 14:46:36.669   588-588   SELinux                 hwservicemanager                     E  avc:  denied  { find } for interface=vendor.dolby.hardware.dms::IDms sid=u:r:priv_app:s0:c512,c768 pid=2717 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:hal_dms_hwservice:s0 tclass=hwservice_manager permissive=0
2025-03-26 14:46:36.670  2717-2872  DmsHalHJ                com.dolby.daxservice                 E  Cannot get HIDL DMS
2025-03-26 14:46:36.670  2717-2872  DmsHalJ                 com.dolby.daxservice                 E  Cannot create DMS HAL instance via either AIDL or HIDL impl.
2025-03-26 14:46:36.670  2717-2872  DaxService              com.dolby.daxservice                 E  initDolbyHalClient, failed to init HAL Dolby client.IDms is null
2025-03-26 14:46:36.670  2717-2872  DaxService              com.dolby.daxservice                 E  mHandler::handleMessage, Reconnect to Dolby service failed, tried 60

Signed-off-by: Arindam Bhattacharjee <abhattacharjee717@gmail.com>

miatoll: Address dolby denial error

2025-03-26 23:41:53.294  2636-2797  DaxService              com.dolby.daxservice                 I  Try to reconnect to Dolby service...
2025-03-26 23:41:53.294  2636-2797  DaxService              com.dolby.daxservice                 D  initDolbyHidlClient()
2025-03-26 23:41:53.298  2636-2797  HidlServiceManagement   com.dolby.daxservice                 W  getService: unable to call into hwbinder service for vendor.dolby.hardware.dms@2.0::IDms/default.
2025-03-26 23:41:53.296  2636-2636  DaxServiceBgThr         com.dolby.daxservice                 W  type=1400 audit(0.0:248): avc:  denied  { call } for  scontext=u:r:priv_app:s0:c512,c768 tcontext=u:r:hal_dms_default:s0 tclass=binder permissive=0 app=com.dolby.daxservice
2025-03-26 23:41:53.299  2636-2797  DaxService              com.dolby.daxservice                 E  initDolbyHidlClient, unable to initiaze service. Unexpected error on connecting to service
                                                                                                    java.util.NoSuchElementException
                                                                                                    	at android.os.HwBinder.getService(Native Method)
                                                                                                    	at android.os.HwBinder.getService(HwBinder.java:93)
                                                                                                    	at vendor.dolby.hardware.dms.V2_0.IDms.getService(IDms.java:77)
                                                                                                    	at vendor.dolby.hardware.dms.V2_0.IDms.getService(IDms.java:87)
                                                                                                    	at com.dolby.daxservice.DaxService.initDolbyHidlClient(DaxService.java:435)
                                                                                                    	at com.dolby.daxservice.DaxService.-314Nest(DaxService.java:0)
                                                                                                    	at com.dolby.daxservice.DaxService.handleMessage(DaxService.java:250)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
2025-03-26 23:41:53.300  2636-2797  DaxService              com.dolby.daxservice                 E  initDolbyHidlClient, failed to init HIDL Dolby client.IDms is null
2025-03-26 23:41:53.300  2636-2797  DaxService              com.dolby.daxservice                 E  mHandler::handleMessage, Reconnect to Dolby service failed, tried 26

Signed-off-by: Arindam Bhattacharjee <abhattacharjee717@gmail.com>